#!/bin/bash
#备份路径
BACKUP=/data/downloadfile/rtls/park1
#当前时间
DATETIME=$(date +%Y-%m-%d-%H%M)

echo "===备份开始==="
 
#数据库名称
DATABASE=park1
#数据库地址
HOST=192.168.1.95
#数据库用户名
DB_USER=root
#数据库密码
DB_PW=tuguiyao
#创建备份目录
[ ! -d "${BACKUP}/$DATETIME" ] && mkdir -p "${BACKUP}/$DATETIME"
echo "备份文件存放于${BACKUP}/$DATABASE-$DATETIME.sql"
#开始备份
/data/docker/dockerdata/tomcatWork/mysqldump -h${HOST}  -u${DB_USER} -p${DB_PW}  ${DATABASE} >${BACKUP}/$DATETIME/$DATABASE-$DATETIME.sql
 
echo "===导出成功，开始传输==="
#压缩成tar.gz包
cd $BACKUP
tar -zcvf $DATETIME.tar.gz $DATETIME
#备份到服务器B
#scp $DATABASE-$DATETIME.sql root@ip:/home/mysqlBackup
#删除备份目录
rm -rf ${BACKUP}/$DATETIME
 
#删除10天（不含）前备份的数据，这边可以自行更改
find $BACKUP -mtime +10 -name "*.tar.gz" -exec rm -rf {} \;
echo "===数据库备份到服务器成功==="
