version: '3'
services:
  #tomcat:
    #image: tomcat
    #container_name: tgy-tomcat
    #tty: true
    #restart: always
    #ports:
      #- "8080:8080"
      #- "3341:3341"
      #- "39777:39777"
      #- "39778:39778/udp"
    #volumes:
      #- /home/chenweibo/docker/DockerFileImages/work/tomcatWork/logs:/usr/local/tomcat/logs
      #- /home/chenweibo/docker/DockerFileImages/work/tomcatWork/webapps:/usr/local/tomcat/webapps
      #- /home/jar:/home/jar
      #- /lib:/lib
      #- /home/uploadfile:/home/uploadfile
      #- /etc/localtime:/etc/localtime
      #- /dev/bus/usb:/dev/bus/usb
    #privileged: true
    #environment:
      #- TZ=Asia/Shanghai
      #- LANG=en_US.UTF-8
    #command:
      #- /bin/bash
      #- -c
      #- |
        #cd /home/jar/
        #./startJar.sh
  redis:
    image: redis
    container_name: tgy-redis
    tty: true
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/chenweibo/docker/DockerFileImages/work/redisWork/data:/data
      - /home/chenweibo/docker/DockerFileImages/work/redisWork/config:/etc/redis/
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
  mysql:
    image: 717160040/mysql5.5
    container_name: tgy-mysql
    tty: true
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /home/chenweibo/docker/DockerFileImages/work/mysqlWork/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      - MYSQL_ROOT_PASSWORD="tgymysql"
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8      
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    tty: true
    restart: always
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    container_name: kafka
    tty: true
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.190
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /data/product/zj_bigdata/data/kafka/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime

  fastdfs-tracker:
    hostname: fastdfs-tracker
    container_name: fastdfs-tracker
    image: season/fastdfs:1.2
    network_mode: "host"
    command: tracker
    volumes:
        - /home/docker/tracker_data:/fastdfs/tracker/data
  fastdfs-storage:
    hostname: fastdfs-storage
    container_name: fastdfs-storage
    image: season/fastdfs:1.2
    network_mode: "host"
    volumes:
       - /home/docker/storage_data:/fastdfs/storage/data
       - /home/docker/store_path:/fastdfs/store_path
    environment:
       - TRACKER_SERVER=192.168.1.190:22122
    command: storage
    depends_on:
       - fastdfs-tracker
  fastdfs-nginx:
    hostname: fastdfs-nginx
    container_name: fastdfs-nginx
    image: season/fastdfs:1.2
    network_mode: "host"
    volumes:
        - /home/docker/nginx.conf:/etc/nginx/conf/nginx.conf
        - /home/docker/store_path:/fastdfs/store_path
    environment:
        - TRACKER_SERVER=192.168.1.190:22122
    command: nginx
#  nacos:
#    image: nacos/nacos-server:1.2.1
#    container_name: nacos
#    restart: always
#    depends_on:
#      - mysql
#    environment:
#      PREFER_HOST_MODE: 192.168.1.190 #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
#      SPRING_DATASOURCE_PLATFORM: mysql #数据源平台 仅支持mysql或不保存empty
#      MODE: standalone
#      MYSQL_SERVICE_HOST: mysql
#      MYSQL_SERVICE_DB_NAME: nacos_devtest
#      MYSQL_SERVICE_PORT: 3306
#      MYSQL_SERVICE_USER: root
#      MYSQL_SERVICE_PASSWORD: tuguiyao     
#      NACOS_APPLICATION_PORT: 8848
#      JVM_XMS: 512m
#      JVM_MMS: 320m
#    volumes:
#      - ./docker/nacos/standalone-logs/:/home/nacos/logs
#      - ./docker/nacos/plugins/:/home/nacos/plugins
#      - ./docker/nacos/conf/application.properties:/home/nacos/conf/application.properties
#    ports:
#      - "8848:8848"
#  prometheus:
#    container_name: prometheus
#    image: prom/prometheus:latest
#    volumes:
#      - ./docker/nacos/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9090:9090"
#    depends_on:
#      - nacos
#    restart: on-failure
#  grafana:
#    container_name: grafana
#    image: grafana/grafana:latest
#    ports:
#      - 3000:3000
#    restart: on-failure
#  cadvisor:
#    image: google/cadvisor:latest
#    container_name: cadvisor
#    restart: always
#    ports:
#      - '8080:8080'
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:rw
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
